# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CERN.
# Copyright (C) 2020 TU Graz.
#
# invenio-shibboleth is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    # To allow failures, you need to specify the full environment
    - env: REQUIREMENTS=devel
    - env: REQUIREMENTS=lowest

cache:
  - pip

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release DEPLOY=true
  - REQUIREMENTS=devel

python:
  - "3.6"
  - "3.7"

before_install:
  - "nvm install 6; nvm use 6"
  - "sudo apt-get install -y libxml2-dev libxmlsec1-dev"
  - "travis_retry pip install wtforms['email']"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e all --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  skip_cleanup: true
  skip_existing: true
  provider: pypi
  username: __token__
  password:
    secure: fn9yW3t+6LYF7bftIrcEFozVGnbdP+fAmNVGUX/Uyc7MqnG9ikXiWIfj7sDUdq1ji8ja1UAyNtPznvVZSIaOvNMYqo3kCGBGFgEz82WmpR5RB7fngA7mzhgkofdECZWcbY4AZxn0zf6Ki3/L7v1S49A7hbEREvjGO2WBAbS2hWpCU8hhvU787qp+w3v4Dv89KG4icfkIe5h2n90HaKCIwCZYhqwIER8eTVwTDS5Hy3UjsOYcQgtUyJN1RLrqtb19Mex/kQFG42da85LsMKS2lUuV5I3jZSZ9Fqo5gU9zQEndUBVMp7E2MsOwr7/3S+0yVXbpJj6aRP/E5g8N6bORczSq0J+Ghl++24Z4GCRH3/V+RdNTO90q08SKFENa2kKuwgFcCzJIVI7xaV57rOsijdatH1tyr8y1vwR9LPbvzGDjFSqIqLPTKhUOhgI67wTb9/urPhFvkfdh/412zlSMWEThYHE/KkjFE6pOPdMOhljZxeRK+Rk/rPF+Fuu5/dB+V6IiPg/Rvpp1pVs3sp3f3JPeOESYRKN7wFUHcMYR23XEMxJGHH1Wn1hh57BQIVC3ngeEq/LMdC7uOfrUBsTWcnCgLr0pnUoBae2fg2og7MxboIuMqPfU5580f6cau8UsFjQ8AeLwtlOgAc8KuozEKS9rs6s7RF5JS0ME4vmEGrY=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "3.7"
    repo: mb-wali/invenio-shibboleth
    condition: $DEPLOY = true
    